-- Add IMPORT to AuditLogAction
ALTER TYPE "AuditLogAction" ADD VALUE IF NOT EXISTS 'IMPORT';

-- Add CURRICULUM_MATRIX and CURRICULUM_MATRIX_ENTRY to AuditLogEntity
ALTER TYPE "AuditLogEntity" ADD VALUE IF NOT EXISTS 'CURRICULUM_MATRIX';
ALTER TYPE "AuditLogEntity" ADD VALUE IF NOT EXISTS 'CURRICULUM_MATRIX_ENTRY';
